- name: Install and Configure NGINX
  hosts: all
  become: yes
  tasks:

    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Copy custom NGINX configuration
      copy:
        src: ./nginx.conf  # Make sure this file exists in the same directory
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart NGINX


    - name: Start and enable NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
